baseURL = 'https://ariztynfansub.github.io/Ariztyn-Fansub/'
languageCode = 'vn'
title = 'Ariztyn-Fansub'
theme = 'hugo-themes-stack'

copyright = 'Bài viết này được cấp phép theo Giấy phép Quốc tế Creative Commons Attribution-ShareAlike 4.0.'
[author]
  name = 'Ariztyno'

repository = "Ariztynfansub/ariztynfansub.github.io"

DefaultContentLanguage = "vn"
hasCJKLanguage = false

# start google config
googleAnalytics = 'G-X2NQ3D3LTX'

enableRobotsTXT = true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
# end google config
	

[taxonomies] 
category = "categories"
tag = "tags"

[permalinks]
post = "/p/:slug/"
page = "/:slug/"
enableEmoji = true #emoj config| list emoji here:https://www.webfx.com/tools/emoji-cheat-sheet/ just copy paste to .md file to use any emoji

[params]
mainSections = [ "post" ]
featuredImageField = "image"
favicon = "/favicon.ico"
rssFullContent = true

  [params.footer]
  since = 2023

  [params.dateFormat]
  published = "02-01-2006"
  lastUpdated = "02-01-2006 15:04 pm GMT+7"

  [params.sidebar]
  compact = false
  subtitle = "Fansub hữu hạn một thành viên"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "cusdis"

	[params.comments.giscus]
		repo = "Ariztynfansub/ariztynfansub.github.io"
		repo-id = "R_kgDOJRqpPQ"
		category = "Q&A"
		category-id = "DIC_kwDOJRqpPc4CVex3"
		mapping = "title"
		strict = "0"
		reactions-enabled = "1"
		emitMetadata = 0
		label = "comment"
		theme = "dark"
		loading = "lazy"
		crossorigin = "anonymous"
	
    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.cactus]
    defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
    serverName = "cactus.chat"
    siteName = ""

    

    [params.comments.gitalk]

    [params.comments.cusdis]
		id = "a104c7ad-8d7e-4e9c-9a59-08b1d3ff7104"
		
		

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"
title = "Danh mục"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 20

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "discord"
  name = "Discord"
  url = "https://discord.gg/rYmq8tk2Ng"
  weight = -90

    [menu.social.params]
    icon = "brand-discord"

  [[menu.social]]
  identifier = "facebook"
  name = "Facebook"
  url = "https://facebook.com/AriztynFansub"
  weight = -80
  
    [menu.social.params]
    icon = "brand-facebook"
	
  [[menu.social]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = -60

    [menu.social.params]
    icon = "rss"
	
  [[menu.social]]
  identifier = "momo"
  name = "Donate via Momo"
  url = "/momo.jpg"
  weight = -70

    [menu.social.params]
    icon = "currency-dong"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = false

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
